lti1p3:
    key_chains:
        kid1:
            key_set_name: "platformSet"
            public_key: "file://%kernel.project_dir%/config/keys/public.key"
            private_key: "file://%kernel.project_dir%/config/keys/private.key"
            private_key_passphrase: ~
        kid2:
            key_set_name: "toolSet"
            public_key: "file://%kernel.project_dir%/config/keys/public.key"
            private_key: "file://%kernel.project_dir%/config/keys/private.key"
            private_key_passphrase: ~
    platforms:
        demoPlatform:
            name: "Demo platform"
            audience: "http://localhost:8888/platform"
            oidc_authentication_url: "http://localhost:8888/lti1p3/oidc/authentication"
            oauth2_access_token_url: "http://localhost:8888/lti1p3/auth/kid1/token" # docker
    tools:
        demoTool:
            name: "Demo tool"
            audience: "http://localhost:8888/tool"
            oidc_initiation_url: "http://localhost:8888/lti1p3/oidc/initiation"
            launch_url: "http://localhost:8888/tool/launch"
            deep_linking_url: "http://localhost:8888/tool/launch/deep-linking"
    registrations:
        demo:
            client_id: "client_id"
            platform: "demoPlatform"
            tool: "demoTool"
            deployment_ids:
                - "deploymentId1"
                - "deploymentId2"
            platform_key_chain: "kid1"
            tool_key_chain: "kid2"
            platform_jwks_url: "http://localhost:8888/lti1p3/.well-known/jwks/platformSet.json"
            tool_jwks_url: "http://localhost:8888/lti1p3/.well-known/jwks/toolSet.json"

