lti1p3:
    key_chains:
        kid1:
            key_set_name: "platformSet"
            public_key: "file://%kernel.project_dir%/config/keys/public.key"
            private_key: "file://%kernel.project_dir%/config/keys/private.key"
            private_key_passphrase: ~
        kid2:
            key_set_name: "toolSet"
            public_key: "file://%kernel.project_dir%/config/keys/public.key"
            private_key: "file://%kernel.project_dir%/config/keys/private.key"
            private_key_passphrase: ~
    platforms:
        localPlatform:
            name: "Local platform"
            audience: "http://localhost:8888/platform"
            oidc_authentication_url: "http://localhost:8888/lti1p3/oidc/authentication"
            oauth2_access_token_url: "http://demo_lti1p3_nginx/lti1p3/auth/kid1/token" # docker
        imsPlatform:
            name: "IMS platform"
            audience: "https://lti-ri.imsglobal.org"
            oidc_authentication_url: "https://lti-ri.imsglobal.org/platforms/978/authorizations/new"
            oauth2_access_token_url: "https://lti-ri.imsglobal.org/platforms/978/access_tokens"
        moodleCloudPlatform:
            name: "Moodle Cloud platform"
            audience: "https://ekkinox.moodlecloud.com"
            oidc_authentication_url: "https://ekkinox.moodlecloud.com/mod/lti/auth.php"
            oauth2_access_token_url: "https://ekkinox.moodlecloud.com/mod/lti/token.php"
    tools:
        localTool:
            name: "Local tool"
            audience: "http://localhost:8888/tool"
            oidc_initiation_url: "http://localhost:8888/lti1p3/oidc/initiation"
            launch_url: "http://localhost:8888/tool/launch"
            deep_linking_url: "http://localhost:8888/tool/launch/deep-linking"
    registrations:
        local:
            client_id: "client_id"
            platform: "localPlatform"
            tool: "localTool"
            deployment_ids:
                - "deploymentId1"
                - "deploymentId2"
            platform_key_chain: "kid1"
            tool_key_chain: "kid2"
            platform_jwks_url: "http://localhost:8888/lti1p3/.well-known/jwks/platformSet.json"
            tool_jwks_url: "http://localhost:8888/lti1p3/.well-known/jwks/toolSet.json"
        imsPlatform:
            client_id: "ims_client_id"
            platform: "imsPlatform"
            tool: "localTool"
            deployment_ids:
                - "imsDeploymentId1"
            platform_key_chain: ~
            tool_key_chain: "kid2"
            platform_jwks_url: "https://lti-ri.imsglobal.org/platforms/978/platform_keys/986.json"
            tool_jwks_url: "http://localhost:8888/lti1p3/.well-known/jwks/toolSet.json"
        moodleCloudPlatform:
            client_id: "7zMfyMq9bshY56E"
            platform: "moodleCloudPlatform"
            tool: "localTool"
            deployment_ids:
                - "1"
            platform_key_chain: ~
            tool_key_chain: "kid2"
            platform_jwks_url: "https://ekkinox.moodlecloud.com/mod/lti/certs.php"
            tool_jwks_url: "http://localhost:8888/lti1p3/.well-known/jwks/toolSet.json"
