security:
    providers:
        users_in_memory: { memory: null }
    firewalls:
        tool_message_area:
            pattern: ^/tool/launch
            stateless: true
            lti1p3_message_tool: true
        platform_service_area:
            pattern: ^/platform/service/ags/
            stateless: true
            lti1p3_service: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: users_in_memory

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
