twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        - '%kernel.project_dir%/vendor/oat-sa/lib-lti1p3-basic-outcome/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        application_version: '%application_version%'
        application_env: '%application_env%'
