parameters:
    deeplinking_resources:
        ltiResourceLinkExample:
            type: ltiResourceLink
            url: http://devkit-lti1p3.localhost/tool/launch
            title: Launch LTI 1.3 DevKit
            text: LTI resource link to launch LTI 1.3 DevKit
            icon:
                url: https://www.taotesting.com/wp-content/uploads/2019/04/favicon-1-300x300.png
            thumbnail:
                url: https://www.taotesting.com/wp-content/uploads/2019/04/favicon-1-300x300.png
        imageExample:
            type: image
            url: https://www.disneyphile.fr/wp-content/uploads/2020/10/fresque-star-wars.png
            title: Star wars (image)
            text: Star wars image
            icon:
                url: https://cdn4.iconfinder.com/data/icons/evil-icons-user-interface/64/picture-20.png
            thumbnail:
                url: https://cdn4.iconfinder.com/data/icons/evil-icons-user-interface/64/picture-20.png
        linkExample:
            type: link
            url: https://en.wikipedia.org/wiki/Star_Wars
            title: Star wars (Wikipedia)
            text: Star wars wikipedia page
            icon:
                url: https://cdn4.iconfinder.com/data/icons/evil-icons-user-interface/64/finger-20.png
            thumbnail:
                url: https://cdn4.iconfinder.com/data/icons/evil-icons-user-interface/64/finger-20.png
        fileExample:
            type: file
            url: http://rbasra.com/images13/jedi.pdf
            title: Jedi path (PDF)
            text: How to become a Jedi (PDF guide)
            icon:
                url: https://cdn4.iconfinder.com/data/icons/48-bubbles/48/12.File-20.png
            thumbnail:
                url: https://cdn4.iconfinder.com/data/icons/48-bubbles/48/12.File-20.png
        htmlFragmentExample:
            type: html
            html: '<div>Hello world</div>'
            title: Hello world (HTML)
            text: HTML fragment to say hello world
