parameters:
    deeplinking_resources:
        ltiResourceLinkExample:
            type: ltiResourceLink
            url: http://localhost:8888/tool/launch
            title: Demo app LTI launch
            text: This is the demo app launch url
            icon:
                url: https://www.iconfinder.com/data/icons/basic-21/32/Basic-iconfinder-22-16.png
            thumbnail:
                url: https://www.iconfinder.com/data/icons/basic-21/32/Basic-iconfinder-22-16.png
        imageExample:
            type: image
            url: https://www.iconfinder.com/data/icons/basic-21/32/Basic-iconfinder-22-16.png
            title: Demo app image
            text: This is the demo app image
            icon:
                url: https://www.iconfinder.com/data/icons/basic-21/32/Basic-iconfinder-22-16.png
            thumbnail:
                url: https://www.iconfinder.com/data/icons/basic-21/32/Basic-iconfinder-22-16.png
        linkExample:
            type: link
            url: https://www.iconfinder.com/data/icons/basic-21/32/Basic-iconfinder-22-16.png
            title: Demo app link
            text: This is the demo app link
            icon:
                url: https://www.iconfinder.com/data/icons/basic-21/32/Basic-iconfinder-22-16.png
            thumbnail:
                url: https://www.iconfinder.com/data/icons/basic-21/32/Basic-iconfinder-22-16.png
