imports:
    - { resource: 'lti1p3/users.yaml' }
    - { resource: 'lti1p3/deep_linking_resources.yaml' }

parameters:
    allowed_scopes:
        - 'https://purl.imsglobal.org/spec/lti-ags/scope/score'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']

    OAT\Library\Lti1p3Core\Security\User\UserAuthenticatorInterface:
        class: App\Security\User\UserAuthenticator

    OAT\Library\Lti1p3Core\User\UserIdentityFactoryInterface:
        class: OAT\Library\Lti1p3Core\User\UserIdentityFactory

    OAT\Library\Lti1p3DeepLinking\Message\Launch\Builder\DeepLinkingLaunchRequestBuilder: ~

    OAT\Library\Lti1p3DeepLinking\Message\Launch\Builder\DeepLinkingLaunchResponseBuilder: ~

    OAT\Library\Lti1p3Nrps\Service\Client\MembershipServiceClient: ~
